version: '2'

services:
    backend:
      image: $IMAGE_DEV
      container_name: $CONTAINER_NAME
      environment:
        VIRTUAL_HOST: $PATH_SERVICE
        EXCLUDE_PORTS: 443
        HOME: /app
        AWS_SDK_LOAD_NONDEFAULT_CONFIG: 1
        AWS_CONFIG_FILE: /app/.aws/config
        AWS_PROFILE: dev
        AWS_SDK_LOAD_CONFIG: 1
      working_dir: /app
      entrypoint: "pnpm start:dev"
      volumes:
        - ./app:/app
        - ~/.aws/:/app/.aws/:rw
#      labels:
#        - lb.hook=true
#      expose:
#        - 80
#        - 9229
      ports:
        - "80:80"

    frontend:
      image: $IMAGE_DEV
      container_name: neoauto-dev-paymentv2doc_frontend
      environment:
        VIRTUAL_HOST: 'local.payment.v2.com/*'
        EXCLUDE_PORTS: 443
        HOME: /app
        AWS_SDK_LOAD_NONDEFAULT_CONFIG: 1
        AWS_CONFIG_FILE: /app/.aws/config
        AWS_PROFILE: dev
        AWS_SDK_LOAD_CONFIG: 1
      working_dir: /app
      entrypoint: "pnpm doc:serve"
      volumes:
        - ./app:/app
        - ~/.aws/:/app/.aws/:rw
      labels:
        - lb.hook=true
      expose:
        - 80

networks:
  default:
    external:
      name: neo_network
