#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/app/node_modules/.pnpm/@compodoc+live-server@1.2.3/node_modules/@compodoc/live-server/node_modules:/app/node_modules/.pnpm/@compodoc+live-server@1.2.3/node_modules/@compodoc/node_modules:/app/node_modules/.pnpm/@compodoc+live-server@1.2.3/node_modules:/app/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/app/node_modules/.pnpm/@compodoc+live-server@1.2.3/node_modules/@compodoc/live-server/node_modules:/app/node_modules/.pnpm/@compodoc+live-server@1.2.3/node_modules/@compodoc/node_modules:/app/node_modules/.pnpm/@compodoc+live-server@1.2.3/node_modules:/app/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../@compodoc+live-server@1.2.3/node_modules/@compodoc/live-server/live-server.js" "$@"
else
  exec node  "$basedir/../../../../../../@compodoc+live-server@1.2.3/node_modules/@compodoc/live-server/live-server.js" "$@"
fi
